MCU = atmega32u4

F_CPU = 16000000

ARCH = AVR8

F_USB = $(F_CPU)

OPT_DEFS += -DINTERRUPT_CONTROL_ENDPOINT

BOOTLOADER = caterina

BOOTMAGIC_ENABLE ?=no
MOUSEKEY_ENABLE ?= no
EXTRAKEY_ENABLE ?= yes
CONSOLE_ENABLE ?= no
COMMAND_ENABLE ?= no
SLEEP_LED_ENABLE ?= no
NKRO_ENABLE ?= yes
BACKLIGHT_ENABLE ?= no
AUDIO_ENABLE ?= no
RGBLIGHT_ENABLE ?= no
